-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 18:13:19 2023
-- Model: Voting    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Voting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Voting` ;

-- -----------------------------------------------------
-- Schema Voting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Voting` ;
USE `Voting` ;

-- -----------------------------------------------------
-- Table `Voting`.`Sex`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Voting`.`Sex` ;

CREATE TABLE IF NOT EXISTS `Voting`.`Sex` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Voting`.`Voter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Voting`.`Voter` ;

CREATE TABLE IF NOT EXISTS `Voting`.`Voter` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `document` INT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `vote` INT UNSIGNED NOT NULL DEFAULT 0,
  `voting_time` TIME NULL,
  `Sex_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Padron_Sex_idx` (`Sex_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `document_UNIQUE` (`document` ASC) VISIBLE,
  CONSTRAINT `fk_Padron_Sex`
    FOREIGN KEY (`Sex_id`)
    REFERENCES `Voting`.`Sex` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Voting`.`Office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Voting`.`Office` ;

CREATE TABLE IF NOT EXISTS `Voting`.`Office` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Voting`.`Contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Voting`.`Contest` ;

CREATE TABLE IF NOT EXISTS `Voting`.`Contest` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Voting`.`Candidate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Voting`.`Candidate` ;

CREATE TABLE IF NOT EXISTS `Voting`.`Candidate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `votes` INT UNSIGNED NOT NULL DEFAULT 0,
  `Office_id` INT UNSIGNED NOT NULL,
  `Contest_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `Office_id`, `Contest_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Candidate_Office1_idx` (`Office_id` ASC) VISIBLE,
  INDEX `fk_Candidate_Contest1_idx` (`Contest_id` ASC) VISIBLE,
  CONSTRAINT `fk_Candidate_Office1`
    FOREIGN KEY (`Office_id`)
    REFERENCES `Voting`.`Office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidate_Contest1`
    FOREIGN KEY (`Contest_id`)
    REFERENCES `Voting`.`Contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Voting`.`Election_Clerk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Voting`.`Election_Clerk` ;

CREATE TABLE IF NOT EXISTS `Voting`.`Election_Clerk` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `opening_time` TIME NULL,
  `closing_time` TIME NULL,
  `username` CHAR(6) NOT NULL,
  `password` CHAR(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
